// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// printUsage
void printUsage(bool verbose);
RcppExport SEXP _fastText_printUsage(SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    printUsage(verbose);
    return R_NilValue;
END_RCPP
}
// printQuantizeUsage
void printQuantizeUsage(bool verbose);
RcppExport SEXP _fastText_printQuantizeUsage(SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    printQuantizeUsage(verbose);
    return R_NilValue;
END_RCPP
}
// printTestUsage
void printTestUsage(bool verbose);
RcppExport SEXP _fastText_printTestUsage(SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    printTestUsage(verbose);
    return R_NilValue;
END_RCPP
}
// printPredictUsage
void printPredictUsage(bool verbose);
RcppExport SEXP _fastText_printPredictUsage(SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    printPredictUsage(verbose);
    return R_NilValue;
END_RCPP
}
// printTestLabelUsage
void printTestLabelUsage(bool verbose);
RcppExport SEXP _fastText_printTestLabelUsage(SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    printTestLabelUsage(verbose);
    return R_NilValue;
END_RCPP
}
// printPrintWordVectorsUsage
void printPrintWordVectorsUsage(bool verbose);
RcppExport SEXP _fastText_printPrintWordVectorsUsage(SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    printPrintWordVectorsUsage(verbose);
    return R_NilValue;
END_RCPP
}
// printPrintSentenceVectorsUsage
void printPrintSentenceVectorsUsage(bool verbose);
RcppExport SEXP _fastText_printPrintSentenceVectorsUsage(SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    printPrintSentenceVectorsUsage(verbose);
    return R_NilValue;
END_RCPP
}
// printPrintNgramsUsage
void printPrintNgramsUsage(bool verbose);
RcppExport SEXP _fastText_printPrintNgramsUsage(SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    printPrintNgramsUsage(verbose);
    return R_NilValue;
END_RCPP
}
// printNNUsage
void printNNUsage(bool verbose);
RcppExport SEXP _fastText_printNNUsage(SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    printNNUsage(verbose);
    return R_NilValue;
END_RCPP
}
// printAnalogiesUsage
void printAnalogiesUsage(bool verbose);
RcppExport SEXP _fastText_printAnalogiesUsage(SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    printAnalogiesUsage(verbose);
    return R_NilValue;
END_RCPP
}
// printDumpUsage
void printDumpUsage(bool verbose);
RcppExport SEXP _fastText_printDumpUsage(SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    printDumpUsage(verbose);
    return R_NilValue;
END_RCPP
}
// give_args_fasttext
void give_args_fasttext(std::vector<std::string> args, std::string pth, int MilliSecs, std::string pth_in, std::string queryWord, bool remove_previous_file);
RcppExport SEXP _fastText_give_args_fasttext(SEXP argsSEXP, SEXP pthSEXP, SEXP MilliSecsSEXP, SEXP pth_inSEXP, SEXP queryWordSEXP, SEXP remove_previous_fileSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type args(argsSEXP);
    Rcpp::traits::input_parameter< std::string >::type pth(pthSEXP);
    Rcpp::traits::input_parameter< int >::type MilliSecs(MilliSecsSEXP);
    Rcpp::traits::input_parameter< std::string >::type pth_in(pth_inSEXP);
    Rcpp::traits::input_parameter< std::string >::type queryWord(queryWordSEXP);
    Rcpp::traits::input_parameter< bool >::type remove_previous_file(remove_previous_fileSEXP);
    give_args_fasttext(args, pth, MilliSecs, pth_in, queryWord, remove_previous_file);
    return R_NilValue;
END_RCPP
}
