// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// printUsage
void printUsage();
RcppExport SEXP _fastText_printUsage() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    printUsage();
    return R_NilValue;
END_RCPP
}
// printQuantizeUsage
void printQuantizeUsage();
RcppExport SEXP _fastText_printQuantizeUsage() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    printQuantizeUsage();
    return R_NilValue;
END_RCPP
}
// printTestUsage
void printTestUsage();
RcppExport SEXP _fastText_printTestUsage() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    printTestUsage();
    return R_NilValue;
END_RCPP
}
// printPredictUsage
void printPredictUsage();
RcppExport SEXP _fastText_printPredictUsage() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    printPredictUsage();
    return R_NilValue;
END_RCPP
}
// printTestLabelUsage
void printTestLabelUsage();
RcppExport SEXP _fastText_printTestLabelUsage() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    printTestLabelUsage();
    return R_NilValue;
END_RCPP
}
// printPrintWordVectorsUsage
void printPrintWordVectorsUsage();
RcppExport SEXP _fastText_printPrintWordVectorsUsage() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    printPrintWordVectorsUsage();
    return R_NilValue;
END_RCPP
}
// printPrintSentenceVectorsUsage
void printPrintSentenceVectorsUsage();
RcppExport SEXP _fastText_printPrintSentenceVectorsUsage() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    printPrintSentenceVectorsUsage();
    return R_NilValue;
END_RCPP
}
// printPrintNgramsUsage
void printPrintNgramsUsage();
RcppExport SEXP _fastText_printPrintNgramsUsage() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    printPrintNgramsUsage();
    return R_NilValue;
END_RCPP
}
// printNNUsage
void printNNUsage();
RcppExport SEXP _fastText_printNNUsage() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    printNNUsage();
    return R_NilValue;
END_RCPP
}
// printAnalogiesUsage
void printAnalogiesUsage();
RcppExport SEXP _fastText_printAnalogiesUsage() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    printAnalogiesUsage();
    return R_NilValue;
END_RCPP
}
// printDumpUsage
void printDumpUsage();
RcppExport SEXP _fastText_printDumpUsage() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    printDumpUsage();
    return R_NilValue;
END_RCPP
}
// give_args_fasttext
void give_args_fasttext(std::vector<std::string> args, std::string pth, int MilliSecs, std::string pth_in, std::string queryWord, bool remove_previous_file);
RcppExport SEXP _fastText_give_args_fasttext(SEXP argsSEXP, SEXP pthSEXP, SEXP MilliSecsSEXP, SEXP pth_inSEXP, SEXP queryWordSEXP, SEXP remove_previous_fileSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<std::string> >::type args(argsSEXP);
    Rcpp::traits::input_parameter< std::string >::type pth(pthSEXP);
    Rcpp::traits::input_parameter< int >::type MilliSecs(MilliSecsSEXP);
    Rcpp::traits::input_parameter< std::string >::type pth_in(pth_inSEXP);
    Rcpp::traits::input_parameter< std::string >::type queryWord(queryWordSEXP);
    Rcpp::traits::input_parameter< bool >::type remove_previous_file(remove_previous_fileSEXP);
    give_args_fasttext(args, pth, MilliSecs, pth_in, queryWord, remove_previous_file);
    return R_NilValue;
END_RCPP
}
