# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Print Usage Information for all parameters
#' 
#' 
#' @export
#' @examples
#' 
#' library(fastText)
#' 
#' printUsage()
#' 
printUsage <- function() {
    invisible(.Call(`_fastText_printUsage`))
}

#' Print Usage Information when the command equals to 'quantize'
#' 
#' 
#' @export
#' @examples
#' 
#' library(fastText)
#' 
#' printQuantizeUsage()
#' 
printQuantizeUsage <- function() {
    invisible(.Call(`_fastText_printQuantizeUsage`))
}

#' Print Usage Information when the command equals to 'test'
#' 
#' 
#' @export
#' @examples
#' 
#' library(fastText)
#' 
#' printTestUsage()
#' 
printTestUsage <- function() {
    invisible(.Call(`_fastText_printTestUsage`))
}

#' Print Usage Information when the command equals to 'predict' or 'predict-prob'
#' 
#' 
#' @export
#' @examples
#' 
#' library(fastText)
#' 
#' printPredictUsage()
#' 
printPredictUsage <- function() {
    invisible(.Call(`_fastText_printPredictUsage`))
}

#' Print Usage Information when the command equals to 'test-label'
#' 
#' 
#' @export
#' @examples
#' 
#' library(fastText)
#' 
#' printTestLabelUsage()
#' 
printTestLabelUsage <- function() {
    invisible(.Call(`_fastText_printTestLabelUsage`))
}

#' Print Usage Information when the command equals to 'print-word-vectors'
#' 
#' 
#' @export
#' @examples
#' 
#' library(fastText)
#' 
#' printPrintWordVectorsUsage()
#' 
printPrintWordVectorsUsage <- function() {
    invisible(.Call(`_fastText_printPrintWordVectorsUsage`))
}

#' Print Usage Information when the command equals to 'print-sentence-vectors'
#' 
#' 
#' @export
#' @examples
#' 
#' library(fastText)
#' 
#' printPrintSentenceVectorsUsage()
#' 
printPrintSentenceVectorsUsage <- function() {
    invisible(.Call(`_fastText_printPrintSentenceVectorsUsage`))
}

#' Print Usage Information when the command equals to 'print-ngrams'
#' 
#' 
#' @export
#' @examples
#' 
#' library(fastText)
#' 
#' printPrintNgramsUsage()
#' 
printPrintNgramsUsage <- function() {
    invisible(.Call(`_fastText_printPrintNgramsUsage`))
}

#' Print Usage Information when the command equals to 'nn'
#' 
#' 
#' @export
#' @examples
#' 
#' library(fastText)
#' 
#' printNNUsage()
#' 
printNNUsage <- function() {
    invisible(.Call(`_fastText_printNNUsage`))
}

#' Print Usage Information when the command equals to 'analogies'
#' 
#' 
#' @export
#' @examples
#' 
#' library(fastText)
#' 
#' printAnalogiesUsage()
#' 
printAnalogiesUsage <- function() {
    invisible(.Call(`_fastText_printAnalogiesUsage`))
}

#' Print Usage Information when the command equals to 'dump'
#' 
#' 
#' @export
#' @examples
#' 
#' library(fastText)
#' 
#' printDumpUsage()
#' 
printDumpUsage <- function() {
    invisible(.Call(`_fastText_printDumpUsage`))
}

#' The Rcpp function which is used in the 'fasttext_interface' R function
#'
#' @keywords internal
#' 
give_args_fasttext <- function(args, pth = "", MilliSecs = 100L, pth_in = "", queryWord = "", remove_previous_file = TRUE) {
    invisible(.Call(`_fastText_give_args_fasttext`, args, pth, MilliSecs, pth_in, queryWord, remove_previous_file))
}

